SYMBOL         = "BTC/USDT"
TIMEFRAME_HTF  = "15m"
TIMEFRAME_LTF  = "1m"

TIMEZONE          = "Europe/Kyiv"
SESSION_START     = "08:00"
SESSION_END       = "12:00"

ACCUMULATION_MIN_CANDLES = 6
ACCUMULATION_MAX_CANDLES = 8

FRACTAL_WINDOW        = 2
CLEAN_REJECTION_RATIO = 0.60

FVG_MIN_SIZE_PCT = 0.001
ENTRY_VARIANT    = "BOTH"

HTF_CANDLES_LIMIT = 100
LTF_CANDLES_LIMIT = 60
LIVE_POLL_SECONDS = 60
